### ISSUE TITLE
how to input an image?

### ISSUE THREAD

**Issue by yangxingyu588** [sachsbl/segmental#1]
hello,when I input an image , I have some problem.so please tell me how to input an image to test.
Thanks,I am a recruit。

**Comment by sachsbl** [comment]
Hey there, thanks for the interest in the project.  Can you describe the error more (or paste the traceback here)?  I just pushed some updates to simplify the CLI and improve the README.  Basically you 

1.  Clone repo
2. Install dependencies using Pip, ideally into a virtual environment
3.  In that environment, run "python segmental_cli.py /Path/to/image.jpg"
4. After a moment (longer the first time you run it), the result will display as a pop-up window.

**Comment by sachsbl** [comment]
make sure you have the latest version of the repo, as the CLI did just change

**Comment by sachsbl** [comment]
closing for lack of action
